--
-- Create Schema Script
--   Database Version            : 18.0.0.0.0
--   Database Compatible Level   : 18.0.0.0.0
--   Script Compatible Level     : 18.0.0.0.0
--   Toad Version                : 13.2.0.258
--   DB Connect String           : XE
--   Schema                      : KPC
--   Script Created by           : KPC
--   Script Created at           : 26/07/2020 13:48:11
--   Notes                       : 
--

-- Object Counts: 
--   Roles: 1           System Privileges: 235  Roles: 17           Grants: 226 
--   Users: 1           System Privileges: 243  Roles: 1                 
--   Tablespaces: 2     Datafiles: 1        Tempfiles: 1 
-- 
--   Directories: 15 
--   Functions: 2       Lines of Code: 83 
--   Object Privileges: 4 
--   Sequences: 1 
--   Tables: 8          Columns: 210        Constraints: 8      


-- "Set define off" turns off substitution variables.
Set define off; 

--
-- DATA_PUMP_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
DATA_PUMP_DIR AS 
'C:\app\WORK\product\18.0.0\admin\xe\dpdump\';


--
-- OPATCH_INST_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
OPATCH_INST_DIR AS 
'C:\app\WORK\product\18.0.0\dbhomeXE\OPatch';


--
-- OPATCH_LOG_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
OPATCH_LOG_DIR AS 
'C:\app\WORK\product\18.0.0\dbhomeXE\rdbms\log';


--
-- OPATCH_SCRIPT_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
OPATCH_SCRIPT_DIR AS 
'C:\app\WORK\product\18.0.0\dbhomeXE\QOpatch';


--
-- ORACLECLRDIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
ORACLECLRDIR AS 
'C:\app\WORK\product\18.0.0\dbhomeXE\bin\clr';


--
-- ORACLE_BASE  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
ORACLE_BASE AS 
'C:\app\WORK\product\18.0.0';


--
-- ORACLE_HOME  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
ORACLE_HOME AS 
'C:\app\WORK\product\18.0.0\dbhomeXE';


--
-- ORACLE_OCM_CONFIG_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
ORACLE_OCM_CONFIG_DIR AS 
'C:\app\WORK\product\18.0.0\dbhomeXE\ccr\state';


--
-- ORACLE_OCM_CONFIG_DIR2  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
ORACLE_OCM_CONFIG_DIR2 AS 
'C:\app\WORK\product\18.0.0\dbhomeXE\ccr\state';


--
-- ORA_DBMS_FCP_ADMINDIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
ORA_DBMS_FCP_ADMINDIR AS 
'C:\app\WORK\product\18.0.0\dbhomeXE\rdbms\admin';


--
-- ORA_DBMS_FCP_LOGDIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
ORA_DBMS_FCP_LOGDIR AS 
'C:\app\WORK\product\18.0.0\dbhomeXE\cfgtoollogs';


--
-- SDO_DIR_ADMIN  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
SDO_DIR_ADMIN AS 
'c:\ade\aime_v\oracle/md/admin';


--
-- SDO_DIR_WORK  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
SDO_DIR_WORK AS 
'';


--
-- XMLDIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XMLDIR AS 
'C:\app\WORK\product\18.0.0\dbhomeXE\rdbms\xml';


--
-- XSDDIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XSDDIR AS 
'C:\app\WORK\product\18.0.0\dbhomeXE\rdbms\xml\schema';


--
-- KPC  (Tablespace) 
--
CREATE TABLESPACE KPC DATAFILE 
  'C:\APP\WORK\PRODUCT\18.0.0\DBHOMEXE\DATABASE\KPC' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
DEFAULT 
  NO INMEMORY
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK OFF;


--
-- TEMP  (Tablespace) 
--
CREATE TEMPORARY TABLESPACE TEMP TEMPFILE 
  'C:\APP\WORK\PRODUCT\18.0.0\ORADATA\XE\TEMP01.DBF' SIZE 32M AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
FLASHBACK ON;


--
-- "DEFAULT"  (Profile) 
--
CREATE PROFILE "DEFAULT" LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION UNLIMITED
  CPU_PER_CALL UNLIMITED
  CONNECT_TIME UNLIMITED
  IDLE_TIME UNLIMITED
  LOGICAL_READS_PER_SESSION UNLIMITED
  LOGICAL_READS_PER_CALL UNLIMITED
  COMPOSITE_LIMIT UNLIMITED
  PRIVATE_SGA UNLIMITED
  FAILED_LOGIN_ATTEMPTS 10
  INACTIVE_ACCOUNT_TIME UNLIMITED
  PASSWORD_LIFE_TIME 180
  PASSWORD_REUSE_TIME UNLIMITED
  PASSWORD_REUSE_MAX UNLIMITED
  PASSWORD_LOCK_TIME 1
  PASSWORD_GRACE_TIME 7
  PASSWORD_VERIFY_FUNCTION NULL;


--
-- DBA  (Role) 
--
CREATE ROLE DBA NOT IDENTIFIED;

-- Object privileges granted to DBA
GRANT EXECUTE ON ORDSYS.CARTRIDGE TO DBA;
GRANT EXECUTE ON SYS.ADR_HOME_T TO DBA;
GRANT EXECUTE ON SYS.ADR_INCIDENT_CORR_KEYS_T TO DBA;
GRANT EXECUTE ON SYS.ADR_INCIDENT_FILES_T TO DBA;
GRANT EXECUTE ON SYS.ADR_INCIDENT_INFO_T TO DBA;
GRANT EXECUTE ON SYS.ADR_INCIDENT_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ARGS_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ARG_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ECID_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ERRID_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_SUPPL_ATTRS_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_SUPPL_ATTR_T TO DBA;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_T TO DBA;
GRANT EXECUTE ON SYS.AS_REPLAY TO DBA;
GRANT SELECT ON SYS.CDB_XS_ACTIVE_SESSIONS TO DBA;
GRANT SELECT ON SYS.CDB_XS_SESSIONS TO DBA;
GRANT SELECT ON SYS.CDB_XS_SESSION_NS_ATTRIBUTES TO DBA;
GRANT SELECT ON SYS.CDB_XS_SESSION_ROLES TO DBA;
GRANT DELETE ON SYS.DBA_REGISTRY_SQLPATCH TO DBA;
GRANT INSERT ON SYS.DBA_REGISTRY_SQLPATCH TO DBA;
GRANT SELECT ON SYS.DBA_REGISTRY_SQLPATCH TO DBA;
GRANT UPDATE ON SYS.DBA_REGISTRY_SQLPATCH TO DBA;
GRANT DELETE ON SYS.DBA_REGISTRY_SQLPATCH_RU_INFO TO DBA;
GRANT INSERT ON SYS.DBA_REGISTRY_SQLPATCH_RU_INFO TO DBA;
GRANT SELECT ON SYS.DBA_REGISTRY_SQLPATCH_RU_INFO TO DBA;
GRANT UPDATE ON SYS.DBA_REGISTRY_SQLPATCH_RU_INFO TO DBA;
GRANT SELECT ON SYS.DBA_XS_ACTIVE_SESSIONS TO DBA;
GRANT SELECT ON SYS.DBA_XS_SESSIONS TO DBA;
GRANT SELECT ON SYS.DBA_XS_SESSION_NS_ATTRIBUTES TO DBA;
GRANT SELECT ON SYS.DBA_XS_SESSION_ROLES TO DBA;
GRANT EXECUTE ON SYS.DBMS_ADR TO DBA;
GRANT EXECUTE ON SYS.DBMS_ADR_APP TO DBA;
GRANT EXECUTE ON SYS.DBMS_APP_CONT TO DBA;
GRANT EXECUTE ON SYS.DBMS_AUTO_SQLTUNE TO DBA;
GRANT EXECUTE ON SYS.DBMS_AUTO_TASK_ADMIN TO DBA;
GRANT EXECUTE ON SYS.DBMS_AUTO_TASK_IMMEDIATE TO DBA;
GRANT EXECUTE ON SYS.DBMS_CACHEUTIL TO DBA;
GRANT EXECUTE ON SYS.DBMS_DNFS TO DBA;
GRANT EXECUTE ON SYS.DBMS_FEATURE_USAGE_REPORT TO DBA;
GRANT EXECUTE ON SYS.DBMS_FLASHBACK TO DBA;
GRANT EXECUTE ON SYS.DBMS_FLASHBACK_ARCHIVE TO DBA;
GRANT EXECUTE ON SYS.DBMS_FS TO DBA;
GRANT EXECUTE ON SYS.DBMS_GSM_FIX TO DBA;
GRANT EXECUTE ON SYS.DBMS_HANG_MANAGER TO DBA;
GRANT EXECUTE ON SYS.DBMS_HM TO DBA;
GRANT EXECUTE ON SYS.DBMS_ILM_ADMIN TO DBA;
GRANT EXECUTE ON SYS.DBMS_INMEMORY_ADMIN TO DBA;
GRANT EXECUTE ON SYS.DBMS_IR TO DBA;
GRANT EXECUTE ON SYS.DBMS_LOGSTDBY TO DBA;
GRANT EXECUTE ON SYS.DBMS_MANAGEMENT_BOOTSTRAP TO DBA;
GRANT EXECUTE ON SYS.DBMS_MONITOR TO DBA;
GRANT EXECUTE ON SYS.DBMS_NETWORK_ACL_ADMIN TO DBA;
GRANT EXECUTE ON SYS.DBMS_PERF TO DBA;
GRANT EXECUTE ON SYS.DBMS_RAT_MASK TO DBA;
GRANT EXECUTE ON SYS.DBMS_RESULT_CACHE TO DBA;
GRANT EXECUTE ON SYS.DBMS_RESUMABLE TO DBA;
GRANT EXECUTE ON SYS.DBMS_ROLLING TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVER_ALERT TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVER_TRACE TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVICE TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVICE_CONST TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVICE_ERR TO DBA;
GRANT EXECUTE ON SYS.DBMS_SERVICE_PRVT TO DBA;
GRANT EXECUTE ON SYS.DBMS_STORAGE_MAP TO DBA;
GRANT EXECUTE ON SYS.DBMS_TDB TO DBA;
GRANT EXECUTE ON SYS.DBMS_TNS TO DBA;
GRANT EXECUTE ON SYS.DBMS_UADV_ARR TO DBA;
GRANT EXECUTE ON SYS.DBMS_UMF TO DBA;
GRANT EXECUTE ON SYS.DBMS_UNDO_ADV TO DBA;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_CAPTURE TO DBA;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPLAY TO DBA;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO DBA;
GRANT EXECUTE ON SYS.DBMS_WRR_STATE TO DBA;
GRANT EXECUTE ON SYS.DBMS_XS_PRINCIPALS TO DBA;
GRANT EXECUTE ON SYS.HM_SQLTK_INTERNAL TO DBA;
GRANT EXECUTE ON SYS.LOAD_UNDO_STAT TO DBA;
GRANT DELETE ON SYS.MAP_OBJECT TO DBA;
GRANT INSERT ON SYS.MAP_OBJECT TO DBA;
GRANT SELECT ON SYS.MAP_OBJECT TO DBA;
GRANT UPDATE ON SYS.MAP_OBJECT TO DBA;
GRANT EXECUTE ON SYS.OJDS_CONTEXT TO DBA;
GRANT EXECUTE ON SYS.ORD_ADMIN TO DBA;
GRANT EXECUTE ON SYS.OUTLN_PKG TO DBA;
GRANT EXECUTE ON SYS.RESET_UNDO_STAT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_ADR_CONTROL TO DBA;
GRANT SELECT ON SYS.V_$DIAG_ADR_CONTROL_AUX TO DBA;
GRANT SELECT ON SYS.V_$DIAG_ADR_INVALIDATION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_ALERT_EXT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_AMS_XACTION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USER_ACTION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USER_ACTION_DEF TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_ACT_PARAM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_ACT_PARAM_DEF TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_INC_ACT_MAP TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_INC_TYPE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_CONFIG_CAPTURE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_CONFIG_ITEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_PATCH_CAPTURE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_PATCH_ITEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_PURGE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DFW_PURGE_ITEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DIAGV_INCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_DIR_EXT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_EM_DIAG_JOB TO DBA;
GRANT SELECT ON SYS.V_$DIAG_EM_TARGET_INFO TO DBA;
GRANT SELECT ON SYS.V_$DIAG_EM_USER_ACTIVITY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_FDG_SET TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_FINDING TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_INFO TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_MESSAGE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_RECOMMENDATION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_HM_RUN TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INCCKEY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INCIDENT_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_CONFIG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_IMPT_DEF TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_INFO TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_PK_IMPTS TO DBA;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_SUMMARY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_CONFIGURATION TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_FILE_COPY_LOG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_FILE_METADATA TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_HISTORY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_INCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PKG_UNPACK_HIST TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_PROGRESS_LOG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_IPS_REMOTE_PACKAGE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_LOG_EXT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_PDB_PROBLEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_PDB_SPACE_MGMT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_PICKLEERR TO DBA;
GRANT SELECT ON SYS.V_$DIAG_PROBLEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_RELMD_EXT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_SWEEPERR TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VEM_USER_ACTLOG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VEM_USER_ACTLOG1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VHM_RUN TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIEW TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIEWCOL TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VINCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VINCIDENT_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VINC_METER_INFO TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_FILE_COPY_LOG TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_FILE_METADATA TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_HISTORY TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_MAIN_INT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_SIZE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_FILE TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_CAND TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_DTL TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_DTL1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_MAIN_PROBLEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VNOT_EXIST_INCIDENT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPDB_PROBLEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM2 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET_COUNT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_INT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_LASTINC TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VSHOWCATVIEW TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VSHOWINCB TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VSHOWINCB_I TO DBA;
GRANT SELECT ON SYS.V_$DIAG_VTEST_EXISTS TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_ACTINC TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_ACTPROB TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_INCCOUNT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_INCFCOUNT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_INC_METER_INFO_PROB TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_IPSPRBCNT TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_IPSPRBCNT1 TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_NFCINC TO DBA;
GRANT SELECT ON SYS.V_$DIAG_V_SWPERRCOUNT TO DBA;
GRANT INSERT ON SYS.XSDB$SCHEMA_ACL TO DBA;
GRANT SELECT ON SYS.XSDB$SCHEMA_ACL TO DBA;
GRANT UPDATE ON SYS.XSDB$SCHEMA_ACL TO DBA;
GRANT EXECUTE ON SYS.XS_MTCACHE_INT TO DBA;
GRANT EXECUTE ON XDB.DBMS_CSX_ADMIN TO DBA;
GRANT EXECUTE ON XDB.DBMS_XDBT TO DBA;
GRANT EXECUTE ON XDB.DBMS_XDB_ADMIN TO DBA;
GRANT DELETE ON XDB.X$PT3HBHABL22E8LPPKKO8O9CW9I2F TO DBA;
GRANT INSERT ON XDB.X$PT3HBHABL22E8LPPKKO8O9CW9I2F TO DBA;
GRANT SELECT ON XDB.X$PT3HBHABL22E8LPPKKO8O9CW9I2F TO DBA;
GRANT UPDATE ON XDB.X$PT3HBHABL22E8LPPKKO8O9CW9I2F TO DBA;
GRANT DELETE ON XDB.XDB$ACL TO DBA;
GRANT INSERT ON XDB.XDB$ACL TO DBA;
GRANT SELECT ON XDB.XDB$ACL TO DBA;
GRANT UPDATE ON XDB.XDB$ACL TO DBA;
GRANT DELETE ON XDB.XDB$CHECKOUTS TO DBA;
GRANT INSERT ON XDB.XDB$CHECKOUTS TO DBA;
GRANT SELECT ON XDB.XDB$CHECKOUTS TO DBA;
GRANT UPDATE ON XDB.XDB$CHECKOUTS TO DBA;
GRANT DELETE ON XDB.XDB$CONFIG TO DBA;
GRANT INSERT ON XDB.XDB$CONFIG TO DBA;
GRANT SELECT ON XDB.XDB$CONFIG TO DBA;
GRANT UPDATE ON XDB.XDB$CONFIG TO DBA;
GRANT DELETE ON XDB.XDB$D_LINK TO DBA;
GRANT INSERT ON XDB.XDB$D_LINK TO DBA;
GRANT SELECT ON XDB.XDB$D_LINK TO DBA;
GRANT UPDATE ON XDB.XDB$D_LINK TO DBA;
GRANT DELETE ON XDB.XDB$H_INDEX TO DBA;
GRANT INSERT ON XDB.XDB$H_INDEX TO DBA;
GRANT SELECT ON XDB.XDB$H_INDEX TO DBA;
GRANT UPDATE ON XDB.XDB$H_INDEX TO DBA;
GRANT DELETE ON XDB.XDB$H_LINK TO DBA;
GRANT INSERT ON XDB.XDB$H_LINK TO DBA;
GRANT SELECT ON XDB.XDB$H_LINK TO DBA;
GRANT UPDATE ON XDB.XDB$H_LINK TO DBA;
GRANT DELETE ON XDB.XDB$NLOCKS TO DBA;
GRANT INSERT ON XDB.XDB$NLOCKS TO DBA;
GRANT SELECT ON XDB.XDB$NLOCKS TO DBA;
GRANT UPDATE ON XDB.XDB$NLOCKS TO DBA;
GRANT DELETE ON XDB.XDB$RESCONFIG TO DBA;
GRANT INSERT ON XDB.XDB$RESCONFIG TO DBA;
GRANT SELECT ON XDB.XDB$RESCONFIG TO DBA;
GRANT UPDATE ON XDB.XDB$RESCONFIG TO DBA;
GRANT DELETE ON XDB.XDB$RESOURCE TO DBA;
GRANT INSERT ON XDB.XDB$RESOURCE TO DBA;
GRANT SELECT ON XDB.XDB$RESOURCE TO DBA;
GRANT UPDATE ON XDB.XDB$RESOURCE TO DBA;

-- System privileges granted to DBA
GRANT ADMINISTER ANY SQL TUNING SET TO DBA CONTAINER=ALL;
GRANT ADMINISTER DATABASE TRIGGER TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'DBA', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO DBA CONTAINER=ALL;
GRANT ADMINISTER SQL TUNING SET TO DBA CONTAINER=ALL;
GRANT ADVISOR TO DBA CONTAINER=ALL;
GRANT ALTER ANY ANALYTIC VIEW TO DBA CONTAINER=ALL;
GRANT ALTER ANY ASSEMBLY TO DBA CONTAINER=ALL;
GRANT ALTER ANY ATTRIBUTE DIMENSION TO DBA CONTAINER=ALL;
GRANT ALTER ANY CLUSTER TO DBA CONTAINER=ALL;
GRANT ALTER ANY CUBE TO DBA CONTAINER=ALL;
GRANT ALTER ANY CUBE BUILD PROCESS TO DBA CONTAINER=ALL;
GRANT ALTER ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT ALTER ANY DIMENSION TO DBA CONTAINER=ALL;
GRANT ALTER ANY EDITION TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY HIERARCHY TO DBA CONTAINER=ALL;
GRANT ALTER ANY INDEX TO DBA CONTAINER=ALL;
GRANT ALTER ANY INDEXTYPE TO DBA CONTAINER=ALL;
GRANT ALTER ANY LIBRARY TO DBA CONTAINER=ALL;
GRANT ALTER ANY MATERIALIZED VIEW TO DBA CONTAINER=ALL;
GRANT ALTER ANY MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT ALTER ANY MINING MODEL TO DBA CONTAINER=ALL;
GRANT ALTER ANY OPERATOR TO DBA CONTAINER=ALL;
GRANT ALTER ANY OUTLINE TO DBA CONTAINER=ALL;
GRANT ALTER ANY PROCEDURE TO DBA CONTAINER=ALL;
GRANT ALTER ANY ROLE TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY SEQUENCE TO DBA CONTAINER=ALL;
GRANT ALTER ANY SQL PROFILE TO DBA CONTAINER=ALL;
GRANT ALTER ANY SQL TRANSLATION PROFILE TO DBA CONTAINER=ALL;
GRANT ALTER ANY TABLE TO DBA CONTAINER=ALL;
GRANT ALTER ANY TRIGGER TO DBA CONTAINER=ALL;
GRANT ALTER ANY TYPE TO DBA CONTAINER=ALL;
GRANT ALTER DATABASE TO DBA CONTAINER=ALL;
GRANT ALTER LOCKDOWN PROFILE TO DBA CONTAINER=ALL;
GRANT ALTER PROFILE TO DBA CONTAINER=ALL;
GRANT ALTER RESOURCE COST TO DBA CONTAINER=ALL;
GRANT ALTER ROLLBACK SEGMENT TO DBA CONTAINER=ALL;
GRANT ALTER SESSION TO DBA CONTAINER=ALL;
GRANT ALTER SYSTEM TO DBA CONTAINER=ALL;
GRANT ALTER TABLESPACE TO DBA CONTAINER=ALL;
GRANT ALTER USER TO DBA CONTAINER=ALL;
GRANT ANALYZE ANY TO DBA CONTAINER=ALL;
GRANT ANALYZE ANY DICTIONARY TO DBA CONTAINER=ALL;
GRANT AUDIT ANY TO DBA CONTAINER=ALL;
GRANT AUDIT SYSTEM TO DBA CONTAINER=ALL;
GRANT BACKUP ANY TABLE TO DBA CONTAINER=ALL;
GRANT BECOME USER TO DBA CONTAINER=ALL;
GRANT CHANGE NOTIFICATION TO DBA CONTAINER=ALL;
GRANT COMMENT ANY MINING MODEL TO DBA CONTAINER=ALL;
GRANT COMMENT ANY TABLE TO DBA CONTAINER=ALL;
GRANT CREATE ANALYTIC VIEW TO DBA CONTAINER=ALL;
GRANT CREATE ANY ANALYTIC VIEW TO DBA CONTAINER=ALL;
GRANT CREATE ANY ASSEMBLY TO DBA CONTAINER=ALL;
GRANT CREATE ANY ATTRIBUTE DIMENSION TO DBA CONTAINER=ALL;
GRANT CREATE ANY CLUSTER TO DBA CONTAINER=ALL;
GRANT CREATE ANY CONTEXT TO DBA CONTAINER=ALL;
GRANT CREATE ANY CREDENTIAL TO DBA CONTAINER=ALL;
GRANT CREATE ANY CUBE TO DBA CONTAINER=ALL;
GRANT CREATE ANY CUBE BUILD PROCESS TO DBA CONTAINER=ALL;
GRANT CREATE ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT CREATE ANY DIMENSION TO DBA CONTAINER=ALL;
GRANT CREATE ANY DIRECTORY TO DBA CONTAINER=ALL;
GRANT CREATE ANY EDITION TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY HIERARCHY TO DBA CONTAINER=ALL;
GRANT CREATE ANY INDEX TO DBA CONTAINER=ALL;
GRANT CREATE ANY INDEXTYPE TO DBA CONTAINER=ALL;
GRANT CREATE ANY JOB TO DBA CONTAINER=ALL;
GRANT CREATE ANY LIBRARY TO DBA CONTAINER=ALL;
GRANT CREATE ANY MATERIALIZED VIEW TO DBA CONTAINER=ALL;
GRANT CREATE ANY MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT CREATE ANY MINING MODEL TO DBA CONTAINER=ALL;
GRANT CREATE ANY OPERATOR TO DBA CONTAINER=ALL;
GRANT CREATE ANY OUTLINE TO DBA CONTAINER=ALL;
GRANT CREATE ANY PROCEDURE TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY SEQUENCE TO DBA CONTAINER=ALL;
GRANT CREATE ANY SQL PROFILE TO DBA CONTAINER=ALL;
GRANT CREATE ANY SQL TRANSLATION PROFILE TO DBA CONTAINER=ALL;
GRANT CREATE ANY SYNONYM TO DBA CONTAINER=ALL;
GRANT CREATE ANY TABLE TO DBA CONTAINER=ALL;
GRANT CREATE ANY TRIGGER TO DBA CONTAINER=ALL;
GRANT CREATE ANY TYPE TO DBA CONTAINER=ALL;
GRANT CREATE ANY VIEW TO DBA CONTAINER=ALL;
GRANT CREATE ASSEMBLY TO DBA CONTAINER=ALL;
GRANT CREATE ATTRIBUTE DIMENSION TO DBA CONTAINER=ALL;
GRANT CREATE CLUSTER TO DBA CONTAINER=ALL;
GRANT CREATE CREDENTIAL TO DBA CONTAINER=ALL;
GRANT CREATE CUBE TO DBA CONTAINER=ALL;
GRANT CREATE CUBE BUILD PROCESS TO DBA CONTAINER=ALL;
GRANT CREATE CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT CREATE DATABASE LINK TO DBA CONTAINER=ALL;
GRANT CREATE DIMENSION TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE EXTERNAL JOB TO DBA CONTAINER=ALL;
GRANT CREATE HIERARCHY TO DBA CONTAINER=ALL;
GRANT CREATE INDEXTYPE TO DBA CONTAINER=ALL;
GRANT CREATE JOB TO DBA CONTAINER=ALL;
GRANT CREATE LIBRARY TO DBA CONTAINER=ALL;
GRANT CREATE LOCKDOWN PROFILE TO DBA CONTAINER=ALL;
GRANT CREATE MATERIALIZED VIEW TO DBA CONTAINER=ALL;
GRANT CREATE MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT CREATE MINING MODEL TO DBA CONTAINER=ALL;
GRANT CREATE OPERATOR TO DBA CONTAINER=ALL;
GRANT CREATE PLUGGABLE DATABASE TO DBA CONTAINER=ALL;
GRANT CREATE PROCEDURE TO DBA CONTAINER=ALL;
GRANT CREATE PROFILE TO DBA CONTAINER=ALL;
GRANT CREATE PUBLIC DATABASE LINK TO DBA CONTAINER=ALL;
GRANT CREATE PUBLIC SYNONYM TO DBA CONTAINER=ALL;
GRANT CREATE ROLE TO DBA CONTAINER=ALL;
GRANT CREATE ROLLBACK SEGMENT TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE SEQUENCE TO DBA CONTAINER=ALL;
GRANT CREATE SESSION TO DBA CONTAINER=ALL;
GRANT CREATE SQL TRANSLATION PROFILE TO DBA CONTAINER=ALL;
GRANT CREATE SYNONYM TO DBA CONTAINER=ALL;
GRANT CREATE TABLE TO DBA CONTAINER=ALL;
GRANT CREATE TABLESPACE TO DBA CONTAINER=ALL;
GRANT CREATE TRIGGER TO DBA CONTAINER=ALL;
GRANT CREATE TYPE TO DBA CONTAINER=ALL;
GRANT CREATE USER TO DBA CONTAINER=ALL;
GRANT CREATE VIEW TO DBA CONTAINER=ALL;
GRANT DEBUG ANY PROCEDURE TO DBA CONTAINER=ALL;
GRANT DEBUG CONNECT SESSION TO DBA CONTAINER=ALL;
GRANT DELETE ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT DELETE ANY MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT DELETE ANY TABLE TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'DBA',
  ADMIN_OPTION => FALSE);
END;
/
GRANT DROP ANY ANALYTIC VIEW TO DBA CONTAINER=ALL;
GRANT DROP ANY ASSEMBLY TO DBA CONTAINER=ALL;
GRANT DROP ANY ATTRIBUTE DIMENSION TO DBA CONTAINER=ALL;
GRANT DROP ANY CLUSTER TO DBA CONTAINER=ALL;
GRANT DROP ANY CONTEXT TO DBA CONTAINER=ALL;
GRANT DROP ANY CUBE TO DBA CONTAINER=ALL;
GRANT DROP ANY CUBE BUILD PROCESS TO DBA CONTAINER=ALL;
GRANT DROP ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT DROP ANY DIMENSION TO DBA CONTAINER=ALL;
GRANT DROP ANY DIRECTORY TO DBA CONTAINER=ALL;
GRANT DROP ANY EDITION TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY HIERARCHY TO DBA CONTAINER=ALL;
GRANT DROP ANY INDEX TO DBA CONTAINER=ALL;
GRANT DROP ANY INDEXTYPE TO DBA CONTAINER=ALL;
GRANT DROP ANY LIBRARY TO DBA CONTAINER=ALL;
GRANT DROP ANY MATERIALIZED VIEW TO DBA CONTAINER=ALL;
GRANT DROP ANY MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT DROP ANY MINING MODEL TO DBA CONTAINER=ALL;
GRANT DROP ANY OPERATOR TO DBA CONTAINER=ALL;
GRANT DROP ANY OUTLINE TO DBA CONTAINER=ALL;
GRANT DROP ANY PROCEDURE TO DBA CONTAINER=ALL;
GRANT DROP ANY ROLE TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY SEQUENCE TO DBA CONTAINER=ALL;
GRANT DROP ANY SQL PROFILE TO DBA CONTAINER=ALL;
GRANT DROP ANY SQL TRANSLATION PROFILE TO DBA CONTAINER=ALL;
GRANT DROP ANY SYNONYM TO DBA CONTAINER=ALL;
GRANT DROP ANY TABLE TO DBA CONTAINER=ALL;
GRANT DROP ANY TRIGGER TO DBA CONTAINER=ALL;
GRANT DROP ANY TYPE TO DBA CONTAINER=ALL;
GRANT DROP ANY VIEW TO DBA CONTAINER=ALL;
GRANT DROP LOCKDOWN PROFILE TO DBA CONTAINER=ALL;
GRANT DROP PROFILE TO DBA CONTAINER=ALL;
GRANT DROP PUBLIC DATABASE LINK TO DBA CONTAINER=ALL;
GRANT DROP PUBLIC SYNONYM TO DBA CONTAINER=ALL;
GRANT DROP ROLLBACK SEGMENT TO DBA CONTAINER=ALL;
GRANT DROP TABLESPACE TO DBA CONTAINER=ALL;
GRANT DROP USER TO DBA CONTAINER=ALL;
GRANT EM EXPRESS CONNECT TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'DBA',
  ADMIN_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY ASSEMBLY TO DBA CONTAINER=ALL;
GRANT EXECUTE ANY CLASS TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY INDEXTYPE TO DBA CONTAINER=ALL;
GRANT EXECUTE ANY LIBRARY TO DBA CONTAINER=ALL;
GRANT EXECUTE ANY OPERATOR TO DBA CONTAINER=ALL;
GRANT EXECUTE ANY PROCEDURE TO DBA CONTAINER=ALL;
GRANT EXECUTE ANY PROGRAM TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY TYPE TO DBA CONTAINER=ALL;
GRANT EXECUTE ASSEMBLY TO DBA CONTAINER=ALL;
GRANT EXPORT FULL DATABASE TO DBA CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO DBA CONTAINER=ALL;
GRANT FLASHBACK ARCHIVE ADMINISTER TO DBA CONTAINER=ALL;
GRANT FORCE ANY TRANSACTION TO DBA CONTAINER=ALL;
GRANT FORCE TRANSACTION TO DBA CONTAINER=ALL;
GRANT GLOBAL QUERY REWRITE TO DBA CONTAINER=ALL;
GRANT GRANT ANY OBJECT PRIVILEGE TO DBA CONTAINER=ALL;
GRANT GRANT ANY PRIVILEGE TO DBA CONTAINER=ALL;
GRANT GRANT ANY ROLE TO DBA CONTAINER=ALL;
GRANT IMPORT FULL DATABASE TO DBA CONTAINER=ALL;
GRANT INSERT ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT INSERT ANY MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT INSERT ANY TABLE TO DBA CONTAINER=ALL;
GRANT LOCK ANY TABLE TO DBA CONTAINER=ALL;
GRANT LOGMINING TO DBA CONTAINER=ALL;
GRANT MANAGE ANY FILE GROUP TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'DBA',
  ADMIN_OPTION => FALSE);
END;
/
GRANT MANAGE FILE GROUP TO DBA CONTAINER=ALL;
GRANT MANAGE SCHEDULER TO DBA CONTAINER=ALL;
GRANT MANAGE TABLESPACE TO DBA CONTAINER=ALL;
GRANT MERGE ANY VIEW TO DBA CONTAINER=ALL;
GRANT ON COMMIT REFRESH TO DBA CONTAINER=ALL;
GRANT QUERY REWRITE TO DBA CONTAINER=ALL;
GRANT READ ANY FILE GROUP TO DBA CONTAINER=ALL;
GRANT READ ANY TABLE TO DBA CONTAINER=ALL;
GRANT REDEFINE ANY TABLE TO DBA CONTAINER=ALL;
GRANT RESTRICTED SESSION TO DBA CONTAINER=ALL;
GRANT RESUMABLE TO DBA CONTAINER=ALL;
GRANT SELECT ANY CUBE TO DBA CONTAINER=ALL;
GRANT SELECT ANY CUBE BUILD PROCESS TO DBA CONTAINER=ALL;
GRANT SELECT ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO DBA CONTAINER=ALL;
GRANT SELECT ANY MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT SELECT ANY MINING MODEL TO DBA CONTAINER=ALL;
GRANT SELECT ANY SEQUENCE TO DBA CONTAINER=ALL;
GRANT SELECT ANY TABLE TO DBA CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO DBA CONTAINER=ALL;
GRANT SET CONTAINER TO DBA CONTAINER=ALL;
GRANT UNDER ANY TABLE TO DBA CONTAINER=ALL;
GRANT UNDER ANY TYPE TO DBA CONTAINER=ALL;
GRANT UNDER ANY VIEW TO DBA CONTAINER=ALL;
GRANT UPDATE ANY CUBE TO DBA CONTAINER=ALL;
GRANT UPDATE ANY CUBE BUILD PROCESS TO DBA CONTAINER=ALL;
GRANT UPDATE ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT UPDATE ANY TABLE TO DBA CONTAINER=ALL;
GRANT USE ANY JOB RESOURCE TO DBA CONTAINER=ALL;
GRANT USE ANY SQL TRANSLATION PROFILE TO DBA CONTAINER=ALL;

-- Roles granted to DBA
--
-- CAPTURE_ADMIN  (Role) 
--
GRANT CAPTURE_ADMIN TO DBA CONTAINER=ALL;
--
-- DATAPUMP_EXP_FULL_DATABASE  (Role) 
--
GRANT DATAPUMP_EXP_FULL_DATABASE TO DBA CONTAINER=ALL;
--
-- DATAPUMP_IMP_FULL_DATABASE  (Role) 
--
GRANT DATAPUMP_IMP_FULL_DATABASE TO DBA CONTAINER=ALL;
--
-- EM_EXPRESS_ALL  (Role) 
--
GRANT EM_EXPRESS_ALL TO DBA CONTAINER=ALL;
--
-- EXECUTE_CATALOG_ROLE  (Role) 
--
GRANT EXECUTE_CATALOG_ROLE TO DBA CONTAINER=ALL;
--
-- EXP_FULL_DATABASE  (Role) 
--
GRANT EXP_FULL_DATABASE TO DBA CONTAINER=ALL;
--
-- GATHER_SYSTEM_STATISTICS  (Role) 
--
GRANT GATHER_SYSTEM_STATISTICS TO DBA CONTAINER=ALL;
--
-- IMP_FULL_DATABASE  (Role) 
--
GRANT IMP_FULL_DATABASE TO DBA CONTAINER=ALL;
--
-- JAVA_ADMIN  (Role) 
--
GRANT JAVA_ADMIN TO DBA CONTAINER=ALL;
--
-- OLAP_DBA  (Role) 
--
GRANT OLAP_DBA TO DBA CONTAINER=ALL;
--
-- OLAP_XS_ADMIN  (Role) 
--
GRANT OLAP_XS_ADMIN TO DBA CONTAINER=ALL;
--
-- OPTIMIZER_PROCESSING_RATE  (Role) 
--
GRANT OPTIMIZER_PROCESSING_RATE TO DBA CONTAINER=ALL;
--
-- SCHEDULER_ADMIN  (Role) 
--
GRANT SCHEDULER_ADMIN TO DBA CONTAINER=ALL;
--
-- SELECT_CATALOG_ROLE  (Role) 
--
GRANT SELECT_CATALOG_ROLE TO DBA CONTAINER=ALL;
--
-- WM_ADMIN_ROLE  (Role) 
--
GRANT WM_ADMIN_ROLE TO DBA CONTAINER=ALL;
--
-- XDBADMIN  (Role) 
--
GRANT XDBADMIN TO DBA CONTAINER=ALL;
--
-- XDB_SET_INVOKER  (Role) 
--
GRANT XDB_SET_INVOKER TO DBA CONTAINER=ALL;


--
-- KPC  (User) 
--
CREATE USER KPC
  IDENTIFIED BY <password>
  HTTP DIGEST DISABLE
  DEFAULT TABLESPACE KPC
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 1 Role for KPC 
--
-- DBA  (Role) 
--
GRANT DBA TO KPC;
ALTER USER KPC DEFAULT ROLE NONE;

-- 243 System Privileges for KPC 
GRANT ALTER ANY ANALYTIC VIEW TO KPC;
GRANT ALTER ANY ASSEMBLY TO KPC;
GRANT ALTER ANY ATTRIBUTE DIMENSION TO KPC;
GRANT ALTER ANY CLUSTER TO KPC;
GRANT ALTER ANY CUBE TO KPC;
GRANT ALTER ANY CUBE BUILD PROCESS TO KPC;
GRANT ALTER ANY CUBE DIMENSION TO KPC;
GRANT ALTER ANY DIMENSION TO KPC;
GRANT ALTER ANY EDITION TO KPC;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY HIERARCHY TO KPC;
GRANT ALTER ANY INDEX TO KPC;
GRANT ALTER ANY INDEXTYPE TO KPC;
GRANT ALTER ANY LIBRARY TO KPC;
GRANT ALTER ANY MATERIALIZED VIEW TO KPC;
GRANT ALTER ANY MEASURE FOLDER TO KPC;
GRANT ALTER ANY MINING MODEL TO KPC;
GRANT ALTER ANY OPERATOR TO KPC;
GRANT ALTER ANY OUTLINE TO KPC;
GRANT ALTER ANY PROCEDURE TO KPC;
GRANT ALTER ANY ROLE TO KPC;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY SEQUENCE TO KPC;
GRANT ALTER ANY SQL PROFILE TO KPC;
GRANT ALTER ANY SQL TRANSLATION PROFILE TO KPC;
GRANT ALTER ANY TABLE TO KPC;
GRANT ALTER ANY TRIGGER TO KPC;
GRANT ALTER ANY TYPE TO KPC;
GRANT ALTER DATABASE TO KPC;
GRANT ALTER DATABASE LINK TO KPC;
GRANT ALTER LOCKDOWN PROFILE TO KPC;
GRANT ALTER PROFILE TO KPC;
GRANT ALTER PUBLIC DATABASE LINK TO KPC;
GRANT ALTER RESOURCE COST TO KPC;
GRANT ALTER ROLLBACK SEGMENT TO KPC;
GRANT ALTER SESSION TO KPC;
GRANT ALTER SYSTEM TO KPC;
GRANT ALTER TABLESPACE TO KPC;
GRANT ALTER USER TO KPC;
GRANT ANALYZE ANY TO KPC;
GRANT ANALYZE ANY DICTIONARY TO KPC;
GRANT AUDIT ANY TO KPC;
GRANT AUDIT SYSTEM TO KPC;
GRANT BACKUP ANY TABLE TO KPC;
GRANT BECOME USER TO KPC;
GRANT CHANGE NOTIFICATION TO KPC;
GRANT COMMENT ANY MINING MODEL TO KPC;
GRANT COMMENT ANY TABLE TO KPC;
GRANT CREATE ANALYTIC VIEW TO KPC;
GRANT CREATE ANY ANALYTIC VIEW TO KPC;
GRANT CREATE ANY ASSEMBLY TO KPC;
GRANT CREATE ANY ATTRIBUTE DIMENSION TO KPC;
GRANT CREATE ANY CLUSTER TO KPC;
GRANT CREATE ANY CONTEXT TO KPC;
GRANT CREATE ANY CREDENTIAL TO KPC;
GRANT CREATE ANY CUBE TO KPC;
GRANT CREATE ANY CUBE BUILD PROCESS TO KPC;
GRANT CREATE ANY CUBE DIMENSION TO KPC;
GRANT CREATE ANY DIMENSION TO KPC;
GRANT CREATE ANY DIRECTORY TO KPC;
GRANT CREATE ANY EDITION TO KPC;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY HIERARCHY TO KPC;
GRANT CREATE ANY INDEX TO KPC;
GRANT CREATE ANY INDEXTYPE TO KPC;
GRANT CREATE ANY JOB TO KPC;
GRANT CREATE ANY LIBRARY TO KPC;
GRANT CREATE ANY MATERIALIZED VIEW TO KPC;
GRANT CREATE ANY MEASURE FOLDER TO KPC;
GRANT CREATE ANY MINING MODEL TO KPC;
GRANT CREATE ANY OPERATOR TO KPC;
GRANT CREATE ANY OUTLINE TO KPC;
GRANT CREATE ANY PROCEDURE TO KPC;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY SEQUENCE TO KPC;
GRANT CREATE ANY SQL PROFILE TO KPC;
GRANT CREATE ANY SQL TRANSLATION PROFILE TO KPC;
GRANT CREATE ANY SYNONYM TO KPC;
GRANT CREATE ANY TABLE TO KPC;
GRANT CREATE ANY TRIGGER TO KPC;
GRANT CREATE ANY TYPE TO KPC;
GRANT CREATE ANY VIEW TO KPC;
GRANT CREATE ASSEMBLY TO KPC;
GRANT CREATE ATTRIBUTE DIMENSION TO KPC;
GRANT CREATE CLUSTER TO KPC;
GRANT CREATE CREDENTIAL TO KPC;
GRANT CREATE CUBE TO KPC;
GRANT CREATE CUBE BUILD PROCESS TO KPC;
GRANT CREATE CUBE DIMENSION TO KPC;
GRANT CREATE DATABASE LINK TO KPC;
GRANT CREATE DIMENSION TO KPC;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE EXTERNAL JOB TO KPC;
GRANT CREATE HIERARCHY TO KPC;
GRANT CREATE INDEXTYPE TO KPC;
GRANT CREATE JOB TO KPC;
GRANT CREATE LIBRARY TO KPC;
GRANT CREATE LOCKDOWN PROFILE TO KPC;
GRANT CREATE MATERIALIZED VIEW TO KPC;
GRANT CREATE MEASURE FOLDER TO KPC;
GRANT CREATE MINING MODEL TO KPC;
GRANT CREATE OPERATOR TO KPC;
GRANT CREATE PLUGGABLE DATABASE TO KPC;
GRANT CREATE PROCEDURE TO KPC;
GRANT CREATE PROFILE TO KPC;
GRANT CREATE PUBLIC DATABASE LINK TO KPC;
GRANT CREATE PUBLIC SYNONYM TO KPC;
GRANT CREATE ROLE TO KPC;
GRANT CREATE ROLLBACK SEGMENT TO KPC;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE SEQUENCE TO KPC;
GRANT CREATE SESSION TO KPC;
GRANT CREATE SQL TRANSLATION PROFILE TO KPC;
GRANT CREATE SYNONYM TO KPC;
GRANT CREATE TABLE TO KPC;
GRANT CREATE TABLESPACE TO KPC;
GRANT CREATE TRIGGER TO KPC;
GRANT CREATE TYPE TO KPC;
GRANT CREATE USER TO KPC;
GRANT CREATE VIEW TO KPC;
GRANT DEBUG ANY PROCEDURE TO KPC;
GRANT DEBUG CONNECT SESSION TO KPC;
GRANT DELETE ANY CUBE DIMENSION TO KPC;
GRANT DELETE ANY MEASURE FOLDER TO KPC;
GRANT DELETE ANY TABLE TO KPC;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'KPC',
  ADMIN_OPTION => FALSE);
END;
/
GRANT DROP ANY ANALYTIC VIEW TO KPC;
GRANT DROP ANY ASSEMBLY TO KPC;
GRANT DROP ANY ATTRIBUTE DIMENSION TO KPC;
GRANT DROP ANY CLUSTER TO KPC;
GRANT DROP ANY CONTEXT TO KPC;
GRANT DROP ANY CUBE TO KPC;
GRANT DROP ANY CUBE BUILD PROCESS TO KPC;
GRANT DROP ANY CUBE DIMENSION TO KPC;
GRANT DROP ANY DIMENSION TO KPC;
GRANT DROP ANY DIRECTORY TO KPC;
GRANT DROP ANY EDITION TO KPC;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY HIERARCHY TO KPC;
GRANT DROP ANY INDEX TO KPC;
GRANT DROP ANY INDEXTYPE TO KPC;
GRANT DROP ANY LIBRARY TO KPC;
GRANT DROP ANY MATERIALIZED VIEW TO KPC;
GRANT DROP ANY MEASURE FOLDER TO KPC;
GRANT DROP ANY MINING MODEL TO KPC;
GRANT DROP ANY OPERATOR TO KPC;
GRANT DROP ANY OUTLINE TO KPC;
GRANT DROP ANY PROCEDURE TO KPC;
GRANT DROP ANY ROLE TO KPC;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY SEQUENCE TO KPC;
GRANT DROP ANY SQL PROFILE TO KPC;
GRANT DROP ANY SQL TRANSLATION PROFILE TO KPC;
GRANT DROP ANY SYNONYM TO KPC;
GRANT DROP ANY TABLE TO KPC;
GRANT DROP ANY TRIGGER TO KPC;
GRANT DROP ANY TYPE TO KPC;
GRANT DROP ANY VIEW TO KPC;
GRANT DROP LOCKDOWN PROFILE TO KPC;
GRANT DROP PROFILE TO KPC;
GRANT DROP PUBLIC DATABASE LINK TO KPC;
GRANT DROP PUBLIC SYNONYM TO KPC;
GRANT DROP ROLLBACK SEGMENT TO KPC;
GRANT DROP TABLESPACE TO KPC;
GRANT DROP USER TO KPC;
GRANT EM EXPRESS CONNECT TO KPC;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'KPC',
  ADMIN_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY ASSEMBLY TO KPC;
GRANT EXECUTE ANY CLASS TO KPC;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY INDEXTYPE TO KPC;
GRANT EXECUTE ANY LIBRARY TO KPC;
GRANT EXECUTE ANY OPERATOR TO KPC;
GRANT EXECUTE ANY PROCEDURE TO KPC;
GRANT EXECUTE ANY PROGRAM TO KPC;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'KPC',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY TYPE TO KPC;
GRANT EXECUTE ASSEMBLY TO KPC;
GRANT EXEMPT ACCESS POLICY TO KPC;
GRANT EXEMPT IDENTITY POLICY TO KPC;
GRANT EXEMPT REDACTION POLICY TO KPC;
GRANT EXPORT FULL DATABASE TO KPC;
GRANT FLASHBACK ANY TABLE TO KPC;
GRANT FLASHBACK ARCHIVE ADMINISTER TO KPC;
GRANT FORCE ANY TRANSACTION TO KPC;
GRANT FORCE TRANSACTION TO KPC;
GRANT GLOBAL QUERY REWRITE TO KPC;
GRANT GRANT ANY OBJECT PRIVILEGE TO KPC;
GRANT GRANT ANY PRIVILEGE TO KPC;
GRANT GRANT ANY ROLE TO KPC;
GRANT IMPORT FULL DATABASE TO KPC;
GRANT INHERIT ANY PRIVILEGES TO KPC;
GRANT INHERIT ANY REMOTE PRIVILEGES TO KPC;
GRANT INSERT ANY CUBE DIMENSION TO KPC;
GRANT INSERT ANY MEASURE FOLDER TO KPC;
GRANT INSERT ANY TABLE TO KPC;
GRANT KEEP DATE TIME TO KPC;
GRANT KEEP SYSGUID TO KPC;
GRANT LOCK ANY TABLE TO KPC;
GRANT LOGMINING TO KPC;
GRANT MANAGE ANY FILE GROUP TO KPC;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'KPC',
  ADMIN_OPTION => FALSE);
END;
/
GRANT MANAGE FILE GROUP TO KPC;
GRANT MANAGE SCHEDULER TO KPC;
GRANT MANAGE TABLESPACE TO KPC;
GRANT MERGE ANY VIEW TO KPC;
GRANT ON COMMIT REFRESH TO KPC;
GRANT PURGE DBA_RECYCLEBIN TO KPC;
GRANT QUERY REWRITE TO KPC;
GRANT READ ANY ANALYTIC VIEW CACHE TO KPC;
GRANT READ ANY FILE GROUP TO KPC;
GRANT READ ANY TABLE TO KPC;
GRANT REDEFINE ANY TABLE TO KPC;
GRANT RESTRICTED SESSION TO KPC;
GRANT RESUMABLE TO KPC;
GRANT SELECT ANY CUBE TO KPC;
GRANT SELECT ANY CUBE BUILD PROCESS TO KPC;
GRANT SELECT ANY CUBE DIMENSION TO KPC;
GRANT SELECT ANY DICTIONARY TO KPC;
GRANT SELECT ANY MEASURE FOLDER TO KPC;
GRANT SELECT ANY MINING MODEL TO KPC;
GRANT SELECT ANY SEQUENCE TO KPC;
GRANT SELECT ANY TABLE TO KPC;
GRANT SELECT ANY TRANSACTION TO KPC;
GRANT SET CONTAINER TO KPC;
GRANT TEXT DATASTORE ACCESS TO KPC;
GRANT TRANSLATE ANY SQL TO KPC;
GRANT UNDER ANY TABLE TO KPC;
GRANT UNDER ANY TYPE TO KPC;
GRANT UNDER ANY VIEW TO KPC;
GRANT UNLIMITED TABLESPACE TO KPC;
GRANT UPDATE ANY CUBE TO KPC;
GRANT UPDATE ANY CUBE BUILD PROCESS TO KPC;
GRANT UPDATE ANY CUBE DIMENSION TO KPC;
GRANT UPDATE ANY TABLE TO KPC;
GRANT USE ANY JOB RESOURCE TO KPC;
GRANT USE ANY SQL TRANSLATION PROFILE TO KPC;
GRANT WRITE ANY ANALYTIC VIEW CACHE TO KPC;


-- Sequence ISEQ$$_74761 is created automatically by Oracle for use with an Identity column


--
-- KRANS  (Table) 
--
--   Row Count: 4
CREATE TABLE KPC.KRANS
(
  KRAN_NAME  VARCHAR2(20 BYTE)                  NOT NULL,
  MAC        VARCHAR2(20 BYTE)                  NOT NULL,
  PROLET     NUMBER(2)
)
TABLESPACE KPC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- LOG  (Table) 
--
--   Row Count: 45
CREATE TABLE KPC.LOG
(
  NAME      VARCHAR2(100 BYTE),
  A         VARCHAR2(50 BYTE),
  B         VARCHAR2(50 BYTE),
  KRAN      VARCHAR2(21 BYTE),
  BRIG      VARCHAR2(21 BYTE),
  STATUS    VARCHAR2(20 BYTE),
  DATE_COM  DATE,
  ID_ROW    NUMBER,
  DATE_OUT  DATE
)
TABLESPACE KPC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- OPP  (Table) 
--
--   Row Count: 44
CREATE TABLE KPC.OPP
(
  ID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1221 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  NAME      VARCHAR2(100 BYTE)                  NOT NULL,
  A         VARCHAR2(100 BYTE),
  B         VARCHAR2(100 BYTE),
  KRAN      VARCHAR2(40 BYTE),
  STATUS    NUMBER(1)                           DEFAULT 0,
  KRAN_MAC  VARCHAR2(50 BYTE),
  PARENT    NUMBER(9)
)
TABLESPACE KPC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- PARTY  (Table) 
--
--   Row Count: 1
CREATE TABLE KPC.PARTY
(
  NUMBERPARTY     VARCHAR2(10 BYTE)             NOT NULL,
  CODEWHEEL       INTEGER,
  FIRSTWHEEL      INTEGER,
  LASTWHEEL       INTEGER,
  TU              VARCHAR2(60 BYTE),
  MELT            VARCHAR2(10 BYTE),
  STANDART        VARCHAR2(60 BYTE),
  DIAMETR         INTEGER,
  BORING          INTEGER,
  DWHOLECENTER    INTEGER,
  STEELMARK       VARCHAR2(50 BYTE),
  QALLZ           INTEGER                       DEFAULT 0,
  QUSEFULZ        INTEGER                       DEFAULT 0,
  BMETALZ         INTEGER                       DEFAULT 0,
  BBLANKZ         INTEGER                       DEFAULT 0,
  USEFULK         INTEGER                       DEFAULT 0,
  BMETALK         INTEGER                       DEFAULT 0,
  BROLLINGK       INTEGER                       DEFAULT 0,
  BTERMOK         INTEGER                       DEFAULT 0,
  BMEHK           INTEGER                       DEFAULT 0,
  BUSC            INTEGER                       DEFAULT 0,
  EVCODE          INTEGER,
  ROLLC           INTEGER,
  ROLLPO          INTEGER,
  HEADC           INTEGER,
  HEADPO          INTEGER,
  HEATER          VARCHAR2(20 BYTE),
  MASTERTU        VARCHAR2(20 BYTE),
  CONTROLEROTKTO  VARCHAR2(20 BYTE),
  CONTROLEROTKFU  VARCHAR2(20 BYTE),
  HEATTREATER     VARCHAR2(20 BYTE),
  MASTEROTK       VARCHAR2(20 BYTE),
  INSPECTORMPS    VARCHAR2(20 BYTE),
  LABENG          VARCHAR2(20 BYTE),
  ST1             INTEGER                       DEFAULT 1,
  ST2             INTEGER                       DEFAULT 1,
  FORMDATE        DATE,
  CHANGEDATE      DATE,
  CONTROL100      INTEGER                       DEFAULT 0,
  NB              INTEGER,
  CONTROL5        VARCHAR2(50 BYTE),
  CONTROL10       VARCHAR2(50 BYTE),
  TIP             VARCHAR2(5 BYTE),
  POURINGDATE     DATE,
  TIPPP           VARCHAR2(5 BYTE),
  YE              VARCHAR2(2 BYTE),
  SDISC           NUMBER(1)                     DEFAULT 0,
  DRAFT           VARCHAR2(60 BYTE),
  WEIGHT          NUMBER,
  MATERIAL        VARCHAR2(30 BYTE),
  C               NUMBER,
  MN              NUMBER,
  SI              NUMBER,
  S               NUMBER,
  P               NUMBER,
  CR              NUMBER,
  NI              NUMBER,
  CU              NUMBER,
  V               NUMBER,
  MO              NUMBER,
  TI              NUMBER,
  KC              NUMBER,
  KMN             NUMBER,
  KSI             NUMBER,
  KS              NUMBER,
  KP              NUMBER,
  KCR             NUMBER,
  KNI             NUMBER,
  KCU             NUMBER,
  KV              NUMBER,
  KMO             NUMBER,
  KTI             NUMBER,
  AL              NUMBER,
  KAL             NUMBER,
  NIOB            NUMBER,
  KNIOB           NUMBER,
  CA              NUMBER,
  KCA             NUMBER,
  H               NUMBER,
  KH              NUMBER,
  MELT_YEAR       VARCHAR2(2 BYTE)
)
TABLESPACE KPC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON COLUMN KPC.PARTY.NUMBERPARTY IS 'номер партии';

COMMENT ON COLUMN KPC.PARTY.CODEWHEEL IS '?';

COMMENT ON COLUMN KPC.PARTY.FIRSTWHEEL IS 'первое колесо';

COMMENT ON COLUMN KPC.PARTY.LASTWHEEL IS 'последнее колесо';

COMMENT ON COLUMN KPC.PARTY.TU IS 'ТУ';

COMMENT ON COLUMN KPC.PARTY.MELT IS 'номер плавки';

COMMENT ON COLUMN KPC.PARTY.STANDART IS 'ГОСТ';

COMMENT ON COLUMN KPC.PARTY.DIAMETR IS 'диаметр';

COMMENT ON COLUMN KPC.PARTY.BORING IS 'расточка';

COMMENT ON COLUMN KPC.PARTY.DWHOLECENTER IS 'диаметр отверстия ступицы';

COMMENT ON COLUMN KPC.PARTY.STEELMARK IS 'марка стали';

COMMENT ON COLUMN KPC.PARTY.QALLZ IS 'Количество всего Заготок';

COMMENT ON COLUMN KPC.PARTY.QUSEFULZ IS 'количество годных заготовок';

COMMENT ON COLUMN KPC.PARTY.BMETALZ IS 'брак металла заготовки';

COMMENT ON COLUMN KPC.PARTY.BBLANKZ IS 'брак заготовок, сделланый на загот участке';

COMMENT ON COLUMN KPC.PARTY.USEFULK IS 'годные колеса';

COMMENT ON COLUMN KPC.PARTY.BMETALK IS 'брак по металлу колес';

COMMENT ON COLUMN KPC.PARTY.BROLLINGK IS 'брак по прокату колес';

COMMENT ON COLUMN KPC.PARTY.BTERMOK IS 'брак по термоучастку колес';

COMMENT ON COLUMN KPC.PARTY.BMEHK IS 'брак мех.обработки колес';

COMMENT ON COLUMN KPC.PARTY.BUSC IS 'брак узк';

COMMENT ON COLUMN KPC.PARTY.EVCODE IS 'код события';

COMMENT ON COLUMN KPC.PARTY.ROLLC IS 'прокатано с № колеса';

COMMENT ON COLUMN KPC.PARTY.ROLLPO IS 'прокатано по № колеса';

COMMENT ON COLUMN KPC.PARTY.HEADC IS 'головные первый №';

COMMENT ON COLUMN KPC.PARTY.HEADPO IS 'головные последжний №';

COMMENT ON COLUMN KPC.PARTY.HEATER IS 'нагревальщик';

COMMENT ON COLUMN KPC.PARTY.MASTERTU IS 'Мастер ТУ';

COMMENT ON COLUMN KPC.PARTY.CONTROLEROTKTO IS 'контроллер ОТКТО';

COMMENT ON COLUMN KPC.PARTY.CONTROLEROTKFU IS 'Контролер ОТК Печи';

COMMENT ON COLUMN KPC.PARTY.HEATTREATER IS 'термист';

COMMENT ON COLUMN KPC.PARTY.MASTEROTK IS 'мастер ОТК';

COMMENT ON COLUMN KPC.PARTY.INSPECTORMPS IS 'инспектор МПС';

COMMENT ON COLUMN KPC.PARTY.LABENG IS 'лабараторный инженер';

COMMENT ON COLUMN KPC.PARTY.ST1 IS 'Ст1 (не знаю)';

COMMENT ON COLUMN KPC.PARTY.ST2 IS 'Ст2 (не знаю)';

COMMENT ON COLUMN KPC.PARTY.FORMDATE IS 'дата формирования партии';

COMMENT ON COLUMN KPC.PARTY.CHANGEDATE IS 'дата изменения партии';

COMMENT ON COLUMN KPC.PARTY.CONTROL100 IS 'контроль 100%';

COMMENT ON COLUMN KPC.PARTY.NB IS 'HB - твердость по Бринелю';

COMMENT ON COLUMN KPC.PARTY.CONTROL5 IS 'контоль на 5 колесах партии';

COMMENT ON COLUMN KPC.PARTY.CONTROL10 IS 'контроль на 10 колесах партии';

COMMENT ON COLUMN KPC.PARTY.TIP IS 'тип';

COMMENT ON COLUMN KPC.PARTY.POURINGDATE IS 'время разливки';

COMMENT ON COLUMN KPC.PARTY.TIPPP IS 'код колеса';

COMMENT ON COLUMN KPC.PARTY.SDISC IS 'тип колес простые(0), S-disc(1), metro(2), Чехия,Словакия и др(3)';

COMMENT ON COLUMN KPC.PARTY.DRAFT IS 'Чертеж';

COMMENT ON COLUMN KPC.PARTY.WEIGHT IS 'теоретический вес колеса';

COMMENT ON COLUMN KPC.PARTY.MATERIAL IS 'номенклатурный номер';

COMMENT ON COLUMN KPC.PARTY.C IS 'углерод';

COMMENT ON COLUMN KPC.PARTY.MN IS 'Марганец';

COMMENT ON COLUMN KPC.PARTY.SI IS 'кремний';

COMMENT ON COLUMN KPC.PARTY.S IS 'сера';

COMMENT ON COLUMN KPC.PARTY.P IS 'фосфор';

COMMENT ON COLUMN KPC.PARTY.CR IS 'хром';

COMMENT ON COLUMN KPC.PARTY.NI IS 'никель';

COMMENT ON COLUMN KPC.PARTY.CU IS 'медь';

COMMENT ON COLUMN KPC.PARTY.V IS 'Ванадий';

COMMENT ON COLUMN KPC.PARTY.MO IS 'молибден';

COMMENT ON COLUMN KPC.PARTY.TI IS 'титан';

COMMENT ON COLUMN KPC.PARTY.KC IS 'углерод (контрольный замер)';

COMMENT ON COLUMN KPC.PARTY.KMN IS 'марганец (контрольный замер)';

COMMENT ON COLUMN KPC.PARTY.KSI IS 'кремний (контрольный замер)';

COMMENT ON COLUMN KPC.PARTY.KS IS 'сера (контрольный замер)';

COMMENT ON COLUMN KPC.PARTY.KP IS 'фосфор (контрольный замер)';

COMMENT ON COLUMN KPC.PARTY.KCR IS 'хром (контрольный замер)';

COMMENT ON COLUMN KPC.PARTY.KNI IS 'никель (контрольный замер)';

COMMENT ON COLUMN KPC.PARTY.KCU IS 'медь (контрольный замер)';

COMMENT ON COLUMN KPC.PARTY.KV IS 'ванадий (контрольный замер)';

COMMENT ON COLUMN KPC.PARTY.KMO IS 'молибден (контрольный замер)';

COMMENT ON COLUMN KPC.PARTY.KTI IS 'Титан (контрольный замер)';

COMMENT ON COLUMN KPC.PARTY.AL IS 'алюминий';

COMMENT ON COLUMN KPC.PARTY.KAL IS 'контрольный алюминий';

COMMENT ON COLUMN KPC.PARTY.NIOB IS 'ниобий';

COMMENT ON COLUMN KPC.PARTY.KNIOB IS 'контрольный ниобий';

COMMENT ON COLUMN KPC.PARTY.CA IS 'кальций';

COMMENT ON COLUMN KPC.PARTY.KCA IS 'кальций (контрольный замер)';

COMMENT ON COLUMN KPC.PARTY.H IS 'водород';

COMMENT ON COLUMN KPC.PARTY.KH IS 'водород(контрольный)';

COMMENT ON COLUMN KPC.PARTY.MELT_YEAR IS 'год плавки';


--
-- PLAV  (Table) 
--
--   Row Count: 16
CREATE TABLE KPC.PLAV
(
  PLAV_NAME  VARCHAR2(50 BYTE),
  COUNT      NUMBER,
  PLACE      VARCHAR2(50 BYTE)
)
TABLESPACE KPC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- SKLAD  (Table) 
--
--   Row Count: 72
CREATE TABLE KPC.SKLAD
(
  NAME       VARCHAR2(15 BYTE)                  NOT NULL,
  MAX_COUNT  NUMBER(10),
  PLACE      VARCHAR2(50 BYTE)                  NOT NULL,
  CUR_COUNT  NUMBER
)
TABLESPACE KPC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- STANDLIST_EXP  (Table) 
--
--   Row Count: 441
CREATE TABLE KPC.STANDLIST_EXP
(
  ID                              NUMBER        NOT NULL,
  YEART                           VARCHAR2(2 BYTE),
  NUMBERWHEEL                     NUMBER,
  NUMBERPARTY                     VARCHAR2(10 BYTE),
  MELT                            VARCHAR2(10 BYTE),
  NUMBERSERT                      NUMBER,
  USEFUL                          VARCHAR2(2 BYTE),
  INSPECTOR                       VARCHAR2(2 BYTE),
  INSPECTORNAME                   VARCHAR2(25 BYTE),
  NDIAMETR                        NUMBER,
  THICKDCENWHEEL                  NUMBER,
  THICKMIDDISK                    NUMBER,
  THICKDRIM                       NUMBER,
  HARDNESS                        NUMBER,
  WIDTHRIM                        NUMBER,
  VDIAMETRNS                      NUMBER,
  VDIAMETRVNS                     NUMBER,
  DIAMETRSTNS                     NUMBER,
  DIAMETRSTVNS                    NUMBER,
  LENCENWHEEL                     NUMBER,
  DIAMETRSLOTST                   NUMBER,
  PASSCIRC                        NUMBER,
  PASSFLATRIM                     NUMBER,
  ECCENTRICITY                    NUMBER,
  DIFFWALLCWNS                    NUMBER,
  DIFFWALLCWVS                    NUMBER,
  DIFFWIDTHRIM                    NUMBER,
  DIFFTHICKRIMNS                  NUMBER,
  DIFFTHICKRIMVS                  NUMBER,
  DIFFTHICKDISCST                 NUMBER,
  DIFFTHICKDISCR                  NUMBER,
  HOGGING                         NUMBER,
  ROUGHDISK                       NUMBER,
  ROUGHSLOTST                     NUMBER,
  ROUGHRIM                        NUMBER,
  ROUGHST                         NUMBER,
  LITMLK                          VARCHAR2(2 BYTE),
  LITUZK                          VARCHAR2(2 BYTE),
  USEFULMLK                       VARCHAR2(2 BYTE),
  USEFULUZK                       VARCHAR2(2 BYTE),
  USERNAME                        VARCHAR2(25 BYTE),
  RECDATE                         DATE,
  NUMBERREQ                       NUMBER,
  NUMBERPACK                      NUMBER,
  PROF                            VARCHAR2(5 BYTE),
  KSGROOVE                        NUMBER,
  TAKEOFF                         NUMBER,
  LENTA                           NUMBER,
  RAZVDIAMETRNS                   NUMBER,
  RAZVDIAMETRVNS                  NUMBER,
  DOPLRIM                         NUMBER,
  DIFFTHICKDISC                   NUMBER,
  LITDROB                         VARCHAR2(2 BYTE),
  KSTHICKRIM                      NUMBER,
  TABNUMSVERL                     VARCHAR2(6 BYTE),
  STANDING                        NUMBER,
  TABNUMDISB                      VARCHAR2(6 BYTE),
  TABNUMTVERDOM                   VARCHAR2(6 BYTE),
  TABNUMMARK                      VARCHAR2(6 BYTE),
  USMARK                          VARCHAR2(2 BYTE),
  USSVERL                         VARCHAR2(2 BYTE),
  USDISB                          VARCHAR2(2 BYTE),
  USTVERD                         VARCHAR2(7 BYTE),
  NUMINPACKAGE                    NUMBER,
  DISBAL                          VARCHAR2(5 BYTE),
  RAZDISBAL                       VARCHAR2(6 BYTE),
  TABNUMINTSIDE                   VARCHAR2(6 BYTE),
  USINTSIDE                       VARCHAR2(2 BYTE),
  YEARTPACK                       VARCHAR2(2 BYTE),
  BLOCKING                        NUMBER        DEFAULT 0,
  HARDNESS2                       NUMBER,
  HARDNESS3                       NUMBER,
  TABNUMPACK                      VARCHAR2(6 BYTE),
  CYLHUBHOLE                      NUMBER,
  DEVPROFVS                       NUMBER,
  DEVPROFNS                       NUMBER,
  WIDTHRIDGE                      NUMBER,
  HEIGHTRIDGE                     NUMBER,
  SURFACERIDGE                    NUMBER,
  DEPTHINDIAM                     NUMBER,
  GROOVEWIDTH                     NUMBER,
  GROOVEDEPTH                     NUMBER,
  GAGEOUTRIM                      NUMBER,
  GROOVEONRIMDIAMETER             NUMBER,
  HUBCYLINDRICALBOREDIAMETER      NUMBER,
  DEPTHBOREHUB                    NUMBER,
  USEFULDROB                      VARCHAR2(2 BYTE),
  TABNUMDROB                      VARCHAR2(6 BYTE),
  EXTERNAL_WHEEL_ID               VARCHAR2(40 BYTE),
  PRELIMINARY_USL                 VARCHAR2(10 BYTE),
  PRELIMINARY_USL_LETTER          VARCHAR2(10 BYTE),
  LAST                            NUMBER,
  DEVIATION_PROFILE_DISC_OUTSIDE  NUMBER,
  DEVIATION_PROFILE_DISC_INSIDE   NUMBER,
  ROUGHDISKNS                     NUMBER,
  ROUGHRIMNS                      NUMBER,
  ROUGHSTNS                       NUMBER,
  ROUGHKRUGKT                     NUMBER,
  AXIALRUNOUTSIDERIM              NUMBER,
  RADIALRUNOUTINNERDIAM           NUMBER
)
TABLESPACE KPC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON TABLE KPC.STANDLIST_EXP IS 'Enjgfybt';

COMMENT ON COLUMN KPC.STANDLIST_EXP.YEART IS 'год';

COMMENT ON COLUMN KPC.STANDLIST_EXP.NUMBERWHEEL IS '№ колеса';

COMMENT ON COLUMN KPC.STANDLIST_EXP.NUMBERPARTY IS '№ партии';

COMMENT ON COLUMN KPC.STANDLIST_EXP.MELT IS '№ плавки';

COMMENT ON COLUMN KPC.STANDLIST_EXP.NUMBERSERT IS '№ сертификата';

COMMENT ON COLUMN KPC.STANDLIST_EXP.USEFUL IS 'годность';

COMMENT ON COLUMN KPC.STANDLIST_EXP.INSPECTOR IS 'литера инспектора';

COMMENT ON COLUMN KPC.STANDLIST_EXP.INSPECTORNAME IS 'Ф.И.О. инспектора';

COMMENT ON COLUMN KPC.STANDLIST_EXP.NDIAMETR IS 'наружний диаметр';

COMMENT ON COLUMN KPC.STANDLIST_EXP.THICKDCENWHEEL IS 'толщина диска ступицы';

COMMENT ON COLUMN KPC.STANDLIST_EXP.THICKMIDDISK IS 'толщина диска в середине';

COMMENT ON COLUMN KPC.STANDLIST_EXP.THICKDRIM IS 'толщина диска обода';

COMMENT ON COLUMN KPC.STANDLIST_EXP.HARDNESS IS 'твердость';

COMMENT ON COLUMN KPC.STANDLIST_EXP.WIDTHRIM IS 'ширина обода';

COMMENT ON COLUMN KPC.STANDLIST_EXP.VDIAMETRNS IS 'внутренний диаметр обода н/с';

COMMENT ON COLUMN KPC.STANDLIST_EXP.VDIAMETRVNS IS 'внутренний диаметр обода в/с';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DIAMETRSTNS IS 'диаметр ступицы н/с';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DIAMETRSTVNS IS 'диаметр ступицы в/с';

COMMENT ON COLUMN KPC.STANDLIST_EXP.LENCENWHEEL IS 'длина ступицы';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DIAMETRSLOTST IS 'диаметр отверстия ступицы';

COMMENT ON COLUMN KPC.STANDLIST_EXP.PASSCIRC IS 'допуск круглости';

COMMENT ON COLUMN KPC.STANDLIST_EXP.PASSFLATRIM IS 'допуск плоскости обода(коробление)';

COMMENT ON COLUMN KPC.STANDLIST_EXP.ECCENTRICITY IS 'эксцентриситет';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DIFFWALLCWNS IS 'разностенность ступицы н/с';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DIFFWALLCWVS IS 'разностенность ступицы в/с';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DIFFWIDTHRIM IS 'разноширинность обода';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DIFFTHICKRIMNS IS 'разнотолщинность обода н/с';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DIFFTHICKRIMVS IS 'разнотолщинность обода в/с';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DIFFTHICKDISCST IS 'разнотолщинность диска ступицы';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DIFFTHICKDISCR IS 'разнотолщинность диска обода';

COMMENT ON COLUMN KPC.STANDLIST_EXP.HOGGING IS 'коробление';

COMMENT ON COLUMN KPC.STANDLIST_EXP.ROUGHDISK IS 'шероховатость диска';

COMMENT ON COLUMN KPC.STANDLIST_EXP.ROUGHSLOTST IS 'шероховат. отв.ступицы';

COMMENT ON COLUMN KPC.STANDLIST_EXP.ROUGHRIM IS 'шероховатость обода';

COMMENT ON COLUMN KPC.STANDLIST_EXP.ROUGHST IS 'шероховатость ступицы';

COMMENT ON COLUMN KPC.STANDLIST_EXP.NUMBERPACK IS '№ упаковки';

COMMENT ON COLUMN KPC.STANDLIST_EXP.PROF IS 'профиль';

COMMENT ON COLUMN KPC.STANDLIST_EXP.KSGROOVE IS 'диаметр проточки';

COMMENT ON COLUMN KPC.STANDLIST_EXP.TAKEOFF IS 'вылет ступицы';

COMMENT ON COLUMN KPC.STANDLIST_EXP.LENTA IS 'лента';

COMMENT ON COLUMN KPC.STANDLIST_EXP.RAZVDIAMETRNS IS 'разница между внутренними диаметрами н/с';

COMMENT ON COLUMN KPC.STANDLIST_EXP.RAZVDIAMETRVNS IS 'разница между внутренними диаметрами в/с';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DOPLRIM IS 'Допуск плоскостности обода';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DIFFTHICKDISC IS 'разнотолщинность диска';

COMMENT ON COLUMN KPC.STANDLIST_EXP.LITDROB IS 'литера контролера ОТК дроб.установки';

COMMENT ON COLUMN KPC.STANDLIST_EXP.KSTHICKRIM IS 'толщина обода';

COMMENT ON COLUMN KPC.STANDLIST_EXP.TABNUMSVERL IS 'табельный номер сверловщика';

COMMENT ON COLUMN KPC.STANDLIST_EXP.STANDING IS 'утопание';

COMMENT ON COLUMN KPC.STANDLIST_EXP.TABNUMDISB IS 'табельный номер дисбалансировщика';

COMMENT ON COLUMN KPC.STANDLIST_EXP.TABNUMTVERDOM IS 'табельный номер твердомера';

COMMENT ON COLUMN KPC.STANDLIST_EXP.TABNUMMARK IS 'табельный номер маркировщика';

COMMENT ON COLUMN KPC.STANDLIST_EXP.USMARK IS 'годность по маркировке';

COMMENT ON COLUMN KPC.STANDLIST_EXP.USSVERL IS 'годность сверловки';

COMMENT ON COLUMN KPC.STANDLIST_EXP.USDISB IS 'годность при дисбалансе';

COMMENT ON COLUMN KPC.STANDLIST_EXP.USTVERD IS 'измерение твердости';

COMMENT ON COLUMN KPC.STANDLIST_EXP.NUMINPACKAGE IS 'Номер в упаковке';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DISBAL IS 'дисбаланс';

COMMENT ON COLUMN KPC.STANDLIST_EXP.RAZDISBAL IS 'размерность дисбаланса';

COMMENT ON COLUMN KPC.STANDLIST_EXP.YEARTPACK IS 'Год упаковки';

COMMENT ON COLUMN KPC.STANDLIST_EXP.BLOCKING IS 'Блокировка колеса(1-заблочено,0 или null - разблокированое)';

COMMENT ON COLUMN KPC.STANDLIST_EXP.HARDNESS2 IS 'Второе значение твердости для пробы';

COMMENT ON COLUMN KPC.STANDLIST_EXP.HARDNESS3 IS 'Третье  значение твердости для пробы';

COMMENT ON COLUMN KPC.STANDLIST_EXP.TABNUMPACK IS 'Табельный номер упаковщика';

COMMENT ON COLUMN KPC.STANDLIST_EXP.CYLHUBHOLE IS 'Цилиндричность отверстия ступицы';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DEVPROFVS IS 'Отклонение от заданного профиля диска с внутренней стороны';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DEVPROFNS IS 'Отклонение от заданного профиля диска с наружней стороны';

COMMENT ON COLUMN KPC.STANDLIST_EXP.WIDTHRIDGE IS 'Ширина (толщина) гребня';

COMMENT ON COLUMN KPC.STANDLIST_EXP.HEIGHTRIDGE IS 'Высота гребня';

COMMENT ON COLUMN KPC.STANDLIST_EXP.SURFACERIDGE IS 'Поверхность гребня';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DEPTHINDIAM IS 'глубина проточки внутреннего диаметра';

COMMENT ON COLUMN KPC.STANDLIST_EXP.GROOVEWIDTH IS 'Ширина выточки';

COMMENT ON COLUMN KPC.STANDLIST_EXP.GROOVEDEPTH IS 'Глубина выточки';

COMMENT ON COLUMN KPC.STANDLIST_EXP.GAGEOUTRIM IS 'разнотолщинность обода снаружи';

COMMENT ON COLUMN KPC.STANDLIST_EXP.GROOVEONRIMDIAMETER IS 'Диаметр канавки на ободе';

COMMENT ON COLUMN KPC.STANDLIST_EXP.HUBCYLINDRICALBOREDIAMETER IS 'Диаметр цилиндрической проточки ступицы';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DEPTHBOREHUB IS 'глубина проточки ступицы';

COMMENT ON COLUMN KPC.STANDLIST_EXP.USEFULDROB IS 'Годность дробеметной обработки колеса';

COMMENT ON COLUMN KPC.STANDLIST_EXP.TABNUMDROB IS 'Табельный номер дробеметной обработки колеса';

COMMENT ON COLUMN KPC.STANDLIST_EXP.EXTERNAL_WHEEL_ID IS 'ID колеса SIEMENS';

COMMENT ON COLUMN KPC.STANDLIST_EXP.PRELIMINARY_USL IS 'Предварительный УЗК';

COMMENT ON COLUMN KPC.STANDLIST_EXP.PRELIMINARY_USL_LETTER IS 'Литера УЗК';

COMMENT ON COLUMN KPC.STANDLIST_EXP.LAST IS 'Признак колес Ласточка (1-ласточка, 0-другие)';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DEVIATION_PROFILE_DISC_OUTSIDE IS 'отклонение от заданного профиля диска (наружняя сторона)';

COMMENT ON COLUMN KPC.STANDLIST_EXP.DEVIATION_PROFILE_DISC_INSIDE IS 'отклонение от заданного профиля диска (внутренняя сторона)';

COMMENT ON COLUMN KPC.STANDLIST_EXP.ROUGHDISKNS IS 'шероховатость диска с наружной стороны';

COMMENT ON COLUMN KPC.STANDLIST_EXP.ROUGHRIMNS IS 'шероховатость обода с наружной стороны';

COMMENT ON COLUMN KPC.STANDLIST_EXP.ROUGHSTNS IS 'шероховатость ступицы с наружной стороны';

COMMENT ON COLUMN KPC.STANDLIST_EXP.ROUGHKRUGKT IS 'шероховатость круга катания';

COMMENT ON COLUMN KPC.STANDLIST_EXP.AXIALRUNOUTSIDERIM IS 'Осевое биение боковой поверхности обода';

COMMENT ON COLUMN KPC.STANDLIST_EXP.RADIALRUNOUTINNERDIAM IS 'Радиальное биение внутреннего диаметра';


--
-- STATUS_TAB  (Table) 
--
--   Row Count: 6
CREATE TABLE KPC.STATUS_TAB
(
  ID    NUMBER,
  NAME  VARCHAR2(35 BYTE)
)
TABLESPACE KPC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- SHIFT_NUMBER  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION KPC.SHIFT_NUMBER (ICURDATE VARCHAR2)
   RETURN NUMBER
IS
   CURDATE    DATE;
   STARTSH    NUMBER := 420;
   ENDSH      NUMBER := 1080;
   STARTSMI   NUMBER := 0;
   ENDSMI     NUMBER := 59;
   H          NUMBER;
   MI         NUMBER;
   OSHIFT     NUMBER;
   ODATET     DATE;
BEGIN
   CURDATE := TO_DATE (ICURDATE, 'dd.mm.yyyy hh24:mi:ss');
   H := (TO_NUMBER (TO_CHAR (CURDATE, 'hh24'))) * 60;
   MI := TO_NUMBER (TO_CHAR (CURDATE, 'mi'));

   IF ( (H + MI) >= (STARTSH + STARTSMI) AND (H + MI) <= (ENDSH + ENDSMI))
   THEN
      OSHIFT := 1;
      ODATET := CURDATE;
   END IF;

   IF ( (H + MI) < (STARTSH + STARTSMI))
   THEN
      OSHIFT := 2;
      ODATET := CURDATE;
   END IF;

   IF ( (H + MI) > (ENDSH + ENDSMI))
   THEN
      OSHIFT := 2;
      ODATET := CURDATE + 1;
   END IF;

   RETURN OSHIFT;
END;
/


--
-- SHIFT_NUM_FUN  (Function) 
--
--  Dependencies: 
--   STANDARD (Package)
--
CREATE OR REPLACE FUNCTION KPC.SHIFT_NUM_FUN (ICURDATE       VARCHAR2,
                                              OSHIFT     OUT VARCHAR2,
                                              ODATET     OUT VARCHAR2)
   RETURN VARCHAR2
IS
   CURDATE    DATE;
   STARTSH    NUMBER := 420;
   ENDSH      NUMBER := 1080;
   STARTSMI   NUMBER := 0;
   ENDSMI     NUMBER := 59;
   H          NUMBER;
   MI         NUMBER;
BEGIN
   CURDATE := TO_DATE (ICURDATE, 'dd.mm.yyyy hh24:mi:ss');
   H := (TO_NUMBER (TO_CHAR (CURDATE, 'hh24'))) * 60;
   MI := TO_NUMBER (TO_CHAR (CURDATE, 'mi'));

   --DBMS_OUTPUT.PUT_LINE ('H: '  H);
   --DBMS_OUTPUT.PUT_LINE ('MI: '  MI);

   --DBMS_OUTPUT.PUT_LINE ('STARTSH: '  STARTSH);
   --DBMS_OUTPUT.PUT_LINE ('STARTSMI: '  STARTSMI);

   --DBMS_OUTPUT.PUT_LINE ('ENDSH: '  ENDSH);
   --DBMS_OUTPUT.PUT_LINE ('ENDSMI: '  ENDSMI);

   IF ( (H + MI) >= (STARTSH + STARTSMI) AND (H + MI) <= (ENDSH + ENDSMI))
   THEN
      OSHIFT := 1;
      ODATET := CURDATE;
   END IF;

   IF ( (H + MI) < (STARTSH + STARTSMI))
   THEN
      OSHIFT := 2;
      ODATET := CURDATE - 1;
   END IF;

   IF ( (H + MI) > (ENDSH + ENDSMI))
   THEN
      OSHIFT := 2;
      ODATET := CURDATE;
   END IF;

   RETURN OSHIFT;
END;
/


GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO EXP_FULL_DATABASE;

GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO IMP_FULL_DATABASE;

GRANT READ, WRITE ON DIRECTORY ORACLE_OCM_CONFIG_DIR TO ORACLE_OCM;

GRANT READ, WRITE ON DIRECTORY ORACLE_OCM_CONFIG_DIR2 TO ORACLE_OCM;
